# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# NOTE: This file is now manually managed to add power-efficient mount options.
# If you regenerate it with nixos-generate-config, re-add the BTRFS options below.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8861b662-52c2-4005-8b66-8795f231dcbc";
      fsType = "btrfs";
      # noatime: skip access-time writes on every file read (less I/O, better SSD longevity)
      # compress=zstd:1: transparent compression reduces read/write amplification
      # space_cache=v2: faster space accounting
      options = [ "subvol=@" "noatime" "compress=zstd:1" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8861b662-52c2-4005-8b66-8795f231dcbc";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd:1" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/930D-05F0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d8456160-504d-440f-8393-3367c6e70ba5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
